// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHIdtTt8_2eb2WzHvCij6YJASeebXvS2I',
    appId: '1:446412825264:web:9e49fd32fc5baa1304d175',
    messagingSenderId: '446412825264',
    projectId: 'maidrent',
    authDomain: 'maidrent.firebaseapp.com',
    storageBucket: 'maidrent.firebasestorage.app',
    measurementId: 'G-YH6RVSG8JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4jBQRCok0OhWJUFnb4Zrb6vXjXElAx_Y',
    appId: '1:446412825264:android:9f79a7b8b1f2ea3f04d175',
    messagingSenderId: '446412825264',
    projectId: 'maidrent',
    storageBucket: 'maidrent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwXUWjSn5sCd0S8-vFfUMC9vgz0qAy6AE',
    appId: '1:446412825264:ios:22865cfbc797671604d175',
    messagingSenderId: '446412825264',
    projectId: 'maidrent',
    storageBucket: 'maidrent.firebasestorage.app',
    iosBundleId: 'com.example.maidRent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwXUWjSn5sCd0S8-vFfUMC9vgz0qAy6AE',
    appId: '1:446412825264:ios:22865cfbc797671604d175',
    messagingSenderId: '446412825264',
    projectId: 'maidrent',
    storageBucket: 'maidrent.firebasestorage.app',
    iosBundleId: 'com.example.maidRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHIdtTt8_2eb2WzHvCij6YJASeebXvS2I',
    appId: '1:446412825264:web:714024eda8695c2a04d175',
    messagingSenderId: '446412825264',
    projectId: 'maidrent',
    authDomain: 'maidrent.firebaseapp.com',
    storageBucket: 'maidrent.firebasestorage.app',
    measurementId: 'G-C66VYJCFN7',
  );
}
